In [1]:
import torch
import numpy
import pandas

In [2]:
x=torch.arange(6).reshape(2,3)
y=torch.tensor([[1,2,3],[4,5,6]])
x*y

tensor([[ 0,  2,  6],
        [12, 20, 30]])

In [3]:
x==y

tensor([[False, False, False],
        [False, False, False]])

In [4]:
before=id(y)
before

1947175541232

In [7]:
c=a@b[:,:2]
c

tensor([[ 150,  160],
        [ 400,  435],
        [ 650,  710],
        [ 900,  985],
        [1150, 1260]])

In [9]:
x=torch.arange(4.)

In [48]:
x.requires_grad_(True)
x.grad.zero_()
y=2*torch.dot(x,x)
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [50]:
x.grad==x*4

tensor([True, True, True, True])