In [1]:
import torch
import torch.nn.functional as F
from torch import nn


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [2]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [3]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.7253e-09, grad_fn=<MeanBackward0>)

In [4]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [5]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.1810,  1.0274, -0.5866],
        [ 0.4476, -1.1254, -0.0448],
        [-3.3659, -0.0726, -0.8766],
        [ 0.8938, -0.3726,  0.6979],
        [ 0.6437, -1.0184, -0.8450]], requires_grad=True)

In [6]:
linear.bias

Parameter containing:
tensor([-1.3161,  0.9663, -0.0939], requires_grad=True)

In [9]:
X=torch.rand(2, 5)
X

tensor([[0.3111, 0.9476, 0.3040, 0.6070, 0.5520],
        [0.5869, 0.8868, 0.7589, 0.1793, 0.9660]])

In [11]:
linear(X)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[13.7544],
        [16.2213]])